### ISSUE TITLE
Placemat example missing workers

### ISSUE THREAD

**Issue by ggilley** [cybozu-go/placemat#104]
The placemat example README describes a boot node and two worker nodes. However, the .yml files only setup the boot node. Would be nice to see a multi-node example.

**Comment by morimoto-cybozu** [comment]
@ggilley 
Oh, yes, that's right.
I'll update the example.
Thanks!

**Comment by morimoto-cybozu** [comment]
@ggilley 
You may need to remove a disk image before retrying.

```console
$ sudo rm /var/scratch/placemat/volumes/boot/seed.img
```
